# Generated by Django 4.0 on 2021-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201101_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='Courses', to='students.Student'),
        ),
    ]
